name: 'Build Notifier'
description: 'This GitHub Action will allow you to take data and send it somewhere.'
branding:
  icon: 'check'
  color: 'gray-dark'

inputs:
  body:
    description: 'The data to send.'
    required: true
  url:
    description: 'The URL you want to send the data to.'
    required: true
  response_code:
    description: 'The expected successful response code from the server to send the data to.'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: |
        npm install
      shell: bash

    - name: Run Action
      run: |
        node invoke-binary.js
      shell: bash
      env:
        BODY: ${{ inputs.body }}
        URL: ${{ inputs.url }}
        RESPONSE_CODE: ${{ inputs.response_code }}
