name: 'CI - CodeQL'

on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
#   schedule:
#     - cron: '0 0 * * MON' # Every Monday.
  workflow_dispatch: # Manual trigger.

jobs:
  one:
    name: one
    runs-on: ubuntu-latest
    
    steps:
      - name: test
        run: |
          echo "test"

  two:
    name: two
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "test"
  fail:
    name: fail
    runs-on: ubuntu-latets
    
    steps:
      - name: fail
        if: ${{ matrix.language == 'python' }}
        run: exit 1

  notification:
    needs: [ one, two, fail ]
    if: always()
    name: Send Build Notification
    runs-on: ubuntu-latest

    steps:
      - name: Webhook
        run: |
          curl --request POST '${{ secrets.WEBHOOK_URL }}' \
            --data "${{ toJSON(needs) }}" \
            --header "Source: GitHub Actions" \
            --header "Content-Type: application/json"
