name: 'Testing'

on:
  workflow_dispatch: # Manual trigger.

jobs:
  one:
    name: one
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo "test"
          echo workflow: ${{ github.workflow }}
          echo repository: ${{ github.repository }}

  two:
    name: two
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "test"
  fail:
    name: fail
    runs-on: ubuntu-latest

    steps:
      - name: fail
        run: exit 1

  notification:
    needs: [one, two, fail]
    if: always()
    name: Send Build Notification
    runs-on: ubuntu-latest

    steps:
      - name: Action Testing
        uses: zchryr/build-notifier-action@v1.0.11
        with:
          body: ${{ toJSON(needs) }}
          url: ${{ secrets.WEBHOOK_URL }}
          response_code: 201
          repo: ${{ github.repository }}
          workflow: ${{ github.workflow }}
